### ISSUE TITLE
Hier könnten wir eine Anforderung hinterlegen

### ISSUE THREAD

**Issue by Pfoerd** [MadEyeRoody/kiml#1]
Cool oder @MadEyeRoody  ;)

**Comment by Pfoerd** [comment]
Sollten wir das benutzen?

**Comment by MadEyeRoody** [comment]
Jo machma

**Comment by MadEyeRoody** [comment]
Ich mach aiuch noch ein Issue rein wo wir am besten reinschreiben vonn wir pushen/ gepusht haben :)
