### ISSUE TITLE
Interaktivität der Wunschliste

### ISSUE THREAD

**Issue by Pfoerd** [MadEyeRoody/kiml#4]
Ich würde mal mit der Interaktivität der Wunschliste machen. @MadEyeRoody oder willst du das machen?

TODOs (aus Mail von Markus):
- Foto
- +/- Prognose pro Wunsch
- optische Anpassung

**Comment by MadEyeRoody** [comment]
ok, mach das ich kümmere mich um die hinweismeldungen auf den empfehlungsseiten. die mache ich also erstes. dann kommen wir uns da noch nicht in die quere. Danach mach ich Design der Startseite.

Bei der Wunschliste sollen dann auch noch die neuen Icons rein (also Variabel berechnet) aber das kann ich wenns ist auch machen :-)

**Comment by MadEyeRoody** [comment]
änderungen in den empfehlung controllern gemacht und gepusht. Kannst darin für die Wunschliste arbeiten.

ich reservier mir mal den Kiml und Home Controller
